FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN DATABASE_URL=mysql://root:root@db:3306/quizmaster_db \
    DATABASE_HOST=db \
    DATABASE_PORT=3306 \
    DATABASE_USER=root \
    DATABASE_PASSWORD=root \
    DATABASE_NAME=quizmaster_db \
    npx prisma generate

RUN npm run build

FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/src/core/infrastructure/generated ./dist/src/core/infrastructure/generated

EXPOSE 3009

CMD ["sh","-c","npx prisma migrate deploy && node dist/src/server.js"]